/*MYSQL存储过程PL/SQL实验*/
DROP PROCEDURE B;
DELIMITER $
CREATE PROCEDURE B()
BEGIN
DECLARE num INT;
SELECT COUNT(*) INTO num FROM cs WHERE Cno='1001';
SELECT AVG(Egrade) AS '平均分数' FROM cs WHERE Cno='1001';
END$
DELIMITER ;
#set @p=1;
#select @p;
#call B(@p);
CALL B();
SELECT * FROM cs WHERE Cno='1001';
/*统计成绩分布*/
DELIMITER $
CREATE PROCEDURE proc1()
BEGIN
SELECT SUM(CASE WHEN Egrade>=60 THEN 1 ELSE 0 END) AS '及格人数',
SUM(CASE WHEN Egrade>=60 THEN 0 ELSE 1 END) AS '不及格人数' FROM cs WHERE Cno='1001';
END$
DELIMITER ;
CALL proc1();
DROP PROCEDURE proc1;
/*统计一门课程的平均成绩*/
DELIMITER $
CREATE PROCEDURE proc2(IN cno VARCHAR(5))
BEGIN
SELECT AVG(Egrade) AS '平均成绩' FROM cs WHERE Cno=cno;
END$
DELIMITER ;
CALL proc2('1001');
DROP PROCEDURE proc2;
/*成绩等级划分*/
DELIMITER $
CREATE PROCEDURE proc3()
BEGIN
ALTER TABLE cs
ADD 等级 CHAR(1);
UPDATE cs
SET 等级='A' WHERE cs.`Egrade` BETWEEN 85 AND 100;
UPDATE cs
SET 等级='B' WHERE cs.`Egrade` BETWEEN 75 AND 85;
UPDATE cs
SET 等级='C' WHERE cs.`Egrade` BETWEEN 75 AND 65;
UPDATE cs
SET 等级='D' WHERE cs.`Egrade` BETWEEN 65 AND 60;
UPDATE cs
SET 等级='E' WHERE cs.`Egrade` <60;
END$
DELIMITER ;
CALL proc3();
DROP PROCEDURE proc3;
SELECT * FROM cs WHERE cs.`Cno`='1001';
